=== DavidCoenFish/ancient-code-0/pipeline/data/schema/materialgrouppacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="arraySubGroupName" type="arraySubGroupNameType"/>
      <xsd:element name="arrayMaterialGroup" type="arrayMaterialGroupType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="arraySubGroupNameType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="arrayMaterialGroupType">
    <xsd:sequence>
      <xsd:element name="materialGroup" type="materialGroupType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="materialGroupType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="needShader" type="xsd:boolean"/>
      <xsd:element name="materialSubGroup" type="materialSubGroupType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="materialSubGroupType">
    <xsd:sequence>
      <xsd:element name="visible" type="xsd:boolean"/>
      <xsd:element name="materialName" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== DavidCoenFish/ancient-code-0/playwithgoldfish/monkey/materialgroup.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/MaterialGroupPacker.xsd"
      >
  
  <arraySubGroupName>
    <name>body</name>
    <name>fin</name>
    <name>eyelid</name>
  </arraySubGroupName>
  
  <arrayMaterialGroup>
    <!--<materialGroup>
      <name>placeholder</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>placeholdermaterial.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>placeholdermaterial.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>placeholdermaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>-->

    <materialGroup>
      <name>orange</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>orangematerialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>orangematerialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>    
    
    <materialGroup>
      <name>white</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>whitematerialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>whitematerialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>

    <materialGroup>
      <name>black</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>blackmaterialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>blackmaterialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>
    
    <materialGroup>
      <name>gold</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>goldmaterialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>goldmaterialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>
    
    <materialGroup>
      <name>chromebump</name>
      <needShader>true</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromebumpmaterialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromebumpmaterialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>

    <materialGroup>
      <name>chromebump2</name>
      <needShader>true</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromebump2materialbody.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromebump2materialfin.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>eyelidmaterial.data</materialName>
      </materialSubGroup>
    </materialGroup>
    
    <materialGroup>
      <name>chrome</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromematerial.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromematerial.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>false</visible>
        <materialName>placeholdermaterialeyelid.data</materialName>
      </materialSubGroup>
    </materialGroup>

    <materialGroup>
      <name>chrome2</name>
      <needShader>false</needShader>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromematerial2.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>true</visible>
        <materialName>chromematerial2.data</materialName>
      </materialSubGroup>
      <materialSubGroup>
        <visible>false</visible>
        <materialName>placeholdermaterialeyelid.data</materialName>
      </materialSubGroup>
    </materialGroup>
    
  </arrayMaterialGroup>
</root>
