=== DavidCoenFish/ancient-code-0/pipeline/data/schema/missionmaster.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="missionList" type="missionListType"/>
      <xsd:element name="genericSequenceList" type="missionListType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="missionListType">
    <xsd:sequence>
      <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/missionmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/missionmaster.xsd"
      >
  
  <missionList>
    <file>mission/missionintro.xml</file>
    <file>mission/missionscene00.xml</file>
    <file>mission/missionscene01.xml</file>
    <file>mission/missionscene02.xml</file>
    <file>mission/missionscene03.xml</file>
    <file>mission/missionscene04.xml</file>
    <file>mission/missionscene05.xml</file>
    <file>mission/missionscene06.xml</file>
    <file>mission/missionscene07.xml</file>
    <file>mission/missionscene08.xml</file>
    <file>mission/missionscene09.xml</file>
    <file>mission/missionscene10.xml</file>
    <file>mission/missionscene11.xml</file>

    <file>mission/missionscenedebug00.xml</file>
    <file>mission/missionscenedebug01.xml</file>
    <file>mission/missionscenedebug02.xml</file>
    <file>mission/missionscenedebug03.xml</file>

  </missionList>
  
  <genericSequenceList>
    <!--<file>mission/genericSequence.xml</file>-->
  </genericSequenceList>


</root>
