=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/animationmaster.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="boneListPosition" type="boneListType" minOccurs="0" />
      <xsd:element name="boneListRotation" type="boneListType" minOccurs="0" />
      <xsd:element name="boneListScale" type="boneListType" minOccurs="0" />
      <xsd:element name="boneListNoteTrack" type="boneListType" minOccurs="0" />
      <xsd:element name="boneListMorphWeight" type="boneListType" minOccurs="0" />
      <xsd:element name="animationList" type="animationListType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="boneListType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="animationListType">
    <xsd:sequence>
      <xsd:element name="file" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== DavidCoenFish/ancient-code-0/beachvolleyball/monkey/reikoanimationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>BoneBall</name>
    <name>Bip01</name>
  </boneListPosition>
  <boneListRotation>
    <name>BoneBall</name>
    <name>Bip01</name>
    <name>Bip01 Pelvis</name>
    <name>Bip01 L Thigh</name>
    <name>Bip01 L Calf</name>
    <name>Bip01 L Foot</name>
    <name>Bip01 L Toe0</name>
    <name>Bip01 L Clavicle</name>
    <name>Bip01 L UpperArm</name>
    <name>Bip01 L Forearm</name>
    <name>Bip01 L Hand</name>
    <name>Bip01 R Thigh</name>
    <name>Bip01 Ponytail1</name>
    <name>Bip01 R Calf</name>
    <name>Bip01 R Foot</name>
    <name>Bip01 R Toe0</name>
    <name>Bip01 R Clavicle</name>
    <name>Bip01 R UpperArm</name>
    <name>Bip01 R Forearm</name>
    <name>Bip01 R Hand</name>
    <name>Bip01 Spine</name>
    <name>Bip01 Spine1</name>
    <name>Bip01 Neck</name>
    <name>Bip01 Head</name>
    <name>BoneLeftBreast</name>
    <name>BoneRightBreast</name>
  </boneListRotation>
  <boneListMorphWeight>
    <name>blink</name>
    <name>speak</name>
    <name>smile</name>
    <!--<name>weird</name>-->
    <name>rightfist</name>
    <name>leftfist</name>
  </boneListMorphWeight>
  <animationList>
    <file>reikoanimation/back.xml</file>
    <file>reikoanimation/fall.xml</file>
    <file>reikoanimation/fallback.xml</file>
    <file>reikoanimation/hithigh.xml</file>
    <file>reikoanimation/hitjump.xml</file>
    <file>reikoanimation/hitlow.xml</file>
    <file>reikoanimation/hitmed.xml</file>
    <file>reikoanimation/idle.xml</file>
    <file>reikoanimation/loosegame.xml</file>
    <file>reikoanimation/loosepoint.xml</file>
    <file>reikoanimation/looseserve.xml</file>
    <file>reikoanimation/menu.xml</file>
    <file>reikoanimation/run.xml</file>
    <file>reikoanimation/serve.xml</file>
    <file>reikoanimation/walk.xml</file>
    <file>reikoanimation/wingame.xml</file>
    <file>reikoanimation/winpoint.xml</file>
    <file>reikoanimation/winserve.xml</file>
  </animationList>
</root>

=== DavidCoenFish/ancient-code-0/playwithgoldfish/monkey/animationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>Bone_head</name>
  </boneListPosition>
  <boneListRotation>
    <name>Bone_head</name>
    <name>Bone_back</name>
    <name>Bone_tail</name>
    <name>Bone_tailright</name>
    <name>Bone_tailleft</name>
    <name>Bone_mouth</name>
    <name>Bone_eyeright</name>
    <name>Bone_eyeleft</name>
    <name>Bone_body</name>
    <name>Bone_thumbleft</name>
    <name>Bone_thumbright</name>
    <name>Bone_fingerleft</name>
    <name>Bone_fingerright</name>
  </boneListRotation>
  <animationList>
    <file>animation/feed.xml</file>
    <file>animation/idle.xml</file>
    <file>animation/idle_agitated.xml</file>
    <file>animation/idle_sleepy.xml</file>
    <file>animation/move.xml</file>
    <file>animation/turn_left.xml</file>
    <file>animation/turn_left_hard.xml</file>
    <file>animation/turn_right.xml</file>
    <file>animation/turn_right_hard.xml</file>
  </animationList>
</root>

=== DavidCoenFish/ancient-code-0/beachvolleyball/monkey/bikinianimationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>BoneBall</name>
    <name>Bip01</name>
  </boneListPosition>
  <boneListRotation>
    <name>BoneBall</name>
    <name>Bip01</name>
    <name>Bip01 Pelvis</name>
    <name>Bip01 L Thigh</name>
    <name>Bip01 L Calf</name>
    <name>Bip01 L Foot</name>
    <name>Bip01 L Toe0</name>
    <name>Bip01 L Clavicle</name>
    <name>Bip01 L UpperArm</name>
    <name>Bip01 L Forearm</name>
    <name>Bip01 L Hand</name>
    <name>Bip01 R Thigh</name>
    <name>Bip01 R Calf</name>
    <name>Bip01 R Foot</name>
    <name>Bip01 R Toe0</name>
    <name>Bip01 R Clavicle</name>
    <name>Bip01 R UpperArm</name>
    <name>Bip01 R Forearm</name>
    <name>Bip01 R Hand</name>
    <name>Bip01 Spine</name>
    <name>Bip01 Spine1</name>
    <name>Bip01 Neck</name>
    <name>Bip01 Head</name>
    <name>BoneLeftBreast</name>
    <name>BoneRightBreast</name>
    <name>BoneLeftBottom</name>
    <name>BoneRightBottom</name>
  </boneListRotation>
  <boneListMorphWeight>
    <name>blink</name>
    <name>speak</name>
    <name>smile</name>
    <!--<name>weird</name>-->
    <name>rightfist</name>
    <name>leftfist</name>
  </boneListMorphWeight>
  <animationList>
    <file>bikinianimation/back.xml</file>
    <file>bikinianimation/fall.xml</file>
    <file>bikinianimation/fallback.xml</file>
    <file>bikinianimation/hithigh.xml</file>
    <file>bikinianimation/hitjump.xml</file>
    <file>bikinianimation/hitlow.xml</file>
    <file>bikinianimation/hitmed.xml</file>
    <file>bikinianimation/idle.xml</file>
    <file>bikinianimation/loosegame.xml</file>
    <file>bikinianimation/loosepoint.xml</file>
    <file>bikinianimation/looseserve.xml</file>
    <file>bikinianimation/menu.xml</file>
    <file>bikinianimation/run.xml</file>
    <file>bikinianimation/serve.xml</file>
    <file>bikinianimation/walk.xml</file>
    <file>bikinianimation/wingame.xml</file>
    <file>bikinianimation/winpoint.xml</file>
    <file>bikinianimation/winserve.xml</file>
  </animationList>
</root>

=== DavidCoenFish/ancient-code-0/beachvolleyball/monkey/cudaanimationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>BoneBall</name>
    <name>Bip01</name>
  </boneListPosition>
  <boneListRotation>
    <name>BoneBall</name>
    <name>Bip01</name>
    <name>Bip01 Pelvis</name>
    <name>Bip01 L Thigh</name>
    <name>Bip01 L Calf</name>
    <name>Bip01 L Foot</name>
    <name>Bip01 L Toe0</name>
    <name>Bip01 L Clavicle</name>
    <name>Bip01 L UpperArm</name>
    <name>Bip01 L Forearm</name>
    <name>Bip01 L Hand</name>
    <name>Bip01 R Thigh</name>
    <name>Bip01 Ponytail1</name>
    <name>Bip01 R Calf</name>
    <name>Bip01 R Foot</name>
    <name>Bip01 R Toe0</name>
    <name>Bip01 R Clavicle</name>
    <name>Bip01 R UpperArm</name>
    <name>Bip01 R Forearm</name>
    <name>Bip01 R Hand</name>
    <name>Bip01 Spine</name>
    <name>Bip01 Spine1</name>
    <name>Bip01 Neck</name>
    <name>Bip01 Head</name>
    <name>BoneLeftBreast</name>
    <name>BoneRightBreast</name>
    <name>BoneLeftBottom</name>
    <name>BoneRightBottom</name>
  </boneListRotation>
  <boneListMorphWeight>
    <name>blink</name>
    <name>speak</name>
    <name>smile</name>
    <!--<name>weird</name>-->
    <name>rightfist</name>
    <name>leftfist</name>
  </boneListMorphWeight>
  <animationList>
    <file>cudaanimation/back.xml</file>
    <file>cudaanimation/fall.xml</file>
    <file>cudaanimation/fallback.xml</file>
    <file>cudaanimation/hithigh.xml</file>
    <file>cudaanimation/hitjump.xml</file>
    <file>cudaanimation/hitlow.xml</file>
    <file>cudaanimation/hitmed.xml</file>
    <file>cudaanimation/idle.xml</file>
    <file>cudaanimation/loosegame.xml</file>
    <file>cudaanimation/loosepoint.xml</file>
    <file>cudaanimation/looseserve.xml</file>
    <file>cudaanimation/menu.xml</file>
    <file>cudaanimation/run.xml</file>
    <file>cudaanimation/serve.xml</file>
    <file>cudaanimation/walk.xml</file>
    <file>cudaanimation/wingame.xml</file>
    <file>cudaanimation/winpoint.xml</file>
    <file>cudaanimation/winserve.xml</file>
  </animationList>
</root>

=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/zombieoneanimationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>Bip01</name>
  </boneListPosition>
  <boneListRotation>
    <name>Bip01</name>
    <name>Bip01 Pelvis</name>
    <name>Bip01 L Thigh</name>
    <name>Bip01 L Calf</name>
    <name>Bip01 L Foot</name>
    <name>Bip01 L Toe0</name>
    <name>Bip01 L Clavicle</name>
    <name>Bip01 L UpperArm</name>
    <name>Bip01 L Forearm</name>
    <name>Bip01 L Hand</name>
    <name>Bip01 L Finger1</name>
    <name>Bip01 L Finger0</name>
    <name>Bip01 R Thigh</name>
    <name>Bip01 R Calf</name>
    <name>Bip01 R Foot</name>
    <name>Bip01 R Toe0</name>
    <name>Bip01 R Clavicle</name>
    <name>Bip01 R UpperArm</name>
    <name>Bip01 R Forearm</name>
    <name>Bip01 R Hand</name>
    <name>Bip01 R Finger1</name>
    <name>Bip01 R Finger0</name>
    <name>Bip01 Spine</name>
    <name>Bip01 Spine1</name>
    <name>Bip01 Neck</name>
    <name>Bip01 Head</name>
    <name>Bip01 Ponytail1</name>
  </boneListRotation>
  <animationList>
    <file>zombieoneanimation/death.xml</file>
 
    <file>zombieoneanimation/idle.xml</file>
    <file>zombieoneanimation/walk.xml</file>
    <file>zombieoneanimation/hop_left.xml</file>
    <file>zombieoneanimation/hop_right.xml</file>
    <file>zombieoneanimation/recoil.xml</file>
    <file>zombieoneanimation/attack_left.xml</file>
    <file>zombieoneanimation/attack_right.xml</file>
    <file>zombieoneanimation/attack_bite.xml</file>

    <file>zombieoneanimation/drag_idle.xml</file>
    <file>zombieoneanimation/drag.xml</file>
    <file>zombieoneanimation/drag_left.xml</file>
    <file>zombieoneanimation/drag_right.xml</file>
    <file>zombieoneanimation/drag_recoil.xml</file>
    <file>zombieoneanimation/drag_attack_left.xml</file>
    <file>zombieoneanimation/drag_attack_right.xml</file>
    <file>zombieoneanimation/drag_attack_bite.xml</file>

  </animationList>
</root>

=== DavidCoenFish/ancient-code-0/beachvolleyball/monkey/aprilanimationmaster.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/animationmaster.xsd"
      >
  <boneListPosition>
    <name>BoneBall</name>
    <name>Bip01</name>
  </boneListPosition>
  <boneListRotation>
    <name>BoneBall</name>
    <name>Bip01</name>
    <name>Bip01 Pelvis</name>
    <name>Bip01 L Thigh</name>
    <name>Bip01 L Calf</name>
    <name>Bip01 L Foot</name>
    <name>Bip01 L Toe0</name>
    <name>Bip01 L Clavicle</name>
    <name>Bip01 L UpperArm</name>
    <name>Bip01 L Forearm</name>
    <name>Bip01 L Hand</name>
    <name>Bip01 R Thigh</name>
    <name>Bip01 Ponytail1</name>
    <name>Bip01 R Calf</name>
    <name>Bip01 R Foot</name>
    <name>Bip01 R Toe0</name>
    <name>Bip01 R Clavicle</name>
    <name>Bip01 R UpperArm</name>
    <name>Bip01 R Forearm</name>
    <name>Bip01 R Hand</name>
    <name>Bip01 Spine</name>
    <name>Bip01 Spine1</name>
    <name>Bip01 Neck</name>
    <name>Bip01 Head</name>
    <name>BoneLeftBreast</name>
    <name>BoneRightBreast</name>
    <name>BoneLeftBottom</name>
    <name>BoneRightBottom</name>
  </boneListRotation>
  <boneListMorphWeight>
    <name>blink</name>
    <name>speak</name>
    <name>smile</name>
    <!--<name>weird</name>-->
    <name>rightfist</name>
    <name>leftfist</name>
  </boneListMorphWeight>
  <animationList>
    <file>aprilanimation/back.xml</file>
    <file>aprilanimation/fall.xml</file>
    <file>aprilanimation/fallback.xml</file>
    <file>aprilanimation/hithigh.xml</file>
    <file>aprilanimation/hitjump.xml</file>
    <file>aprilanimation/hitlow.xml</file>
    <file>aprilanimation/hitmed.xml</file>
    <file>aprilanimation/idle.xml</file>
    <file>aprilanimation/loosegame.xml</file>
    <file>aprilanimation/loosepoint.xml</file>
    <file>aprilanimation/looseserve.xml</file>
    <file>aprilanimation/menu.xml</file>
    <file>aprilanimation/run.xml</file>
    <file>aprilanimation/serve.xml</file>
    <file>aprilanimation/walk.xml</file>
    <file>aprilanimation/wingame.xml</file>
    <file>aprilanimation/winpoint.xml</file>
    <file>aprilanimation/winserve.xml</file>    
  </animationList>
</root>
