=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/fontpacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="spaceWidth" type="xsd:integer"/>
      <xsd:element name="newLine" type="xsd:integer"/>
      <xsd:element name="fontDataArray" type="fontDataArrayType"/>
      <xsd:element name="destination" type="destinationType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="fontDataArrayType">
    <xsd:sequence>
      <xsd:element name="fontData" type="fontDataType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="fontDataType">
    <xsd:sequence>
      <xsd:element name="filePath" type="xsd:string"/>
      <xsd:element name="value" type="xsd:integer"/>
      <xsd:element name="baseLine" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="destinationType">
    <xsd:sequence>
      <xsd:element name="tagetTexture" type="xsd:string"/>
      <xsd:element name="targetWidth" type="xsd:integer" />
      <xsd:element name="targetHeight" type="xsd:integer" />
      <xsd:element name="writeOriginX" type="xsd:integer" />
      <xsd:element name="writeOriginY" type="xsd:integer" />
      <xsd:element name="writeWidth" type="xsd:integer" />
      <xsd:element name="writeHeight" type="xsd:integer" />
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/fontverdanasplit.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/fontpacker.xsd">
    <spaceWidth>22</spaceWidth>
    <newLine>54</newLine>
    <fontDataArray>
        <fontData>
            <filePath>fontveranda\char_00000021.tga</filePath>
            <value>33</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000022.tga</filePath>
            <value>34</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000023.tga</filePath>
            <value>35</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000024.tga</filePath>
            <value>36</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000025.tga</filePath>
            <value>37</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000026.tga</filePath>
            <value>38</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000027.tga</filePath>
            <value>39</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000028.tga</filePath>
            <value>40</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000029.tga</filePath>
            <value>41</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002a.tga</filePath>
            <value>42</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002b.tga</filePath>
            <value>43</value>
            <baseLine>-96</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002c.tga</filePath>
            <value>44</value>
            <baseLine>-123</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002d.tga</filePath>
            <value>45</value>
            <baseLine>-111</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002e.tga</filePath>
            <value>46</value>
            <baseLine>-123</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000002f.tga</filePath>
            <value>47</value>
            <baseLine>-89</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000030.tga</filePath>
            <value>48</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000031.tga</filePath>
            <value>49</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000032.tga</filePath>
            <value>50</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000033.tga</filePath>
            <value>51</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000034.tga</filePath>
            <value>52</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000035.tga</filePath>
            <value>53</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000036.tga</filePath>
            <value>54</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000037.tga</filePath>
            <value>55</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000038.tga</filePath>
            <value>56</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000039.tga</filePath>
            <value>57</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003a.tga</filePath>
            <value>58</value>
            <baseLine>-102</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003b.tga</filePath>
            <value>59</value>
            <baseLine>-102</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003c.tga</filePath>
            <value>60</value>
            <baseLine>-96</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003d.tga</filePath>
            <value>61</value>
            <baseLine>-104</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003e.tga</filePath>
            <value>62</value>
            <baseLine>-96</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000003f.tga</filePath>
            <value>63</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000040.tga</filePath>
            <value>64</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000041.tga</filePath>
            <value>65</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000042.tga</filePath>
            <value>66</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000043.tga</filePath>
            <value>67</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000044.tga</filePath>
            <value>68</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000045.tga</filePath>
            <value>69</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000046.tga</filePath>
            <value>70</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000047.tga</filePath>
            <value>71</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000048.tga</filePath>
            <value>72</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000049.tga</filePath>
            <value>73</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004a.tga</filePath>
            <value>74</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004b.tga</filePath>
            <value>75</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004c.tga</filePath>
            <value>76</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004d.tga</filePath>
            <value>77</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004e.tga</filePath>
            <value>78</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000004f.tga</filePath>
            <value>79</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000050.tga</filePath>
            <value>80</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000051.tga</filePath>
            <value>81</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000052.tga</filePath>
            <value>82</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000053.tga</filePath>
            <value>83</value>
            <baseLine>-90</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000054.tga</filePath>
            <value>84</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000055.tga</filePath>
            <value>85</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000056.tga</filePath>
            <value>86</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000057.tga</filePath>
            <value>87</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000058.tga</filePath>
            <value>88</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_00000059.tga</filePath>
            <value>89</value>
            <baseLine>-91</baseLine>
        </fontData>
        <fontData>
            <filePath>fontveranda\char_0000005a.tga</filePath>
            <value>90</value>
            <baseLine>-91</baseLine>
