=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/fontspliter.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="source" type="sourceType"/>
      <xsd:element name="destination" type="destinationType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="sourceType">
    <xsd:sequence>
      <xsd:element name="spaceWidth" type="xsd:integer"/>
      <xsd:element name="newLine" type="xsd:integer"/>
      <xsd:element name="image" type="imageType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="imageType">
    <xsd:sequence>
      <xsd:element name="filePath" type="xsd:string"/>
      <xsd:element name="charSequence" type="xsd:string"/>
      <xsd:element name="baseLine" type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="destinationType">
    <xsd:sequence>
      <xsd:element name="destinationPath" type="xsd:string"/>
      <xsd:element name="tagetTexture" type="xsd:string"/>
      <xsd:element name="targetWidth" type="xsd:integer" />
      <xsd:element name="targetHeight" type="xsd:integer" />
      <xsd:element name="writeOriginX" type="xsd:integer" />
      <xsd:element name="writeOriginY" type="xsd:integer" />
      <xsd:element name="writeWidth" type="xsd:integer" />
      <xsd:element name="writeHeight" type="xsd:integer" />
    </xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== DavidCoenFish/ancient-code-0/pipeline/data/fontspliter.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/fontspliter.xsd"
      >
  <source>
    <spaceWidth>22</spaceWidth>
    <newLine>26</newLine>
    <image>
      <filePath>fontspliter/alphanumeric_dejavu_italic_32.tga</filePath>
      <!--<charSequence>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890`~!@#$%^*()_+-=[]{};':",./?\|&#169;</charSequence>-->
      <charSequence>&#169;</charSequence>
      <baseLine>30</baseLine>
    </image>
  </source>
  
  <destination>
    <destinationPath>fontspliterout\</destinationPath>
    <tagetTexture>fonttest.tga</tagetTexture>
    <targetWidth>2048</targetWidth>
    <targetHeight>2048</targetHeight>
    <writeOriginX>512</writeOriginX>
    <writeOriginY>1024</writeOriginY>
    <writeWidth>512</writeWidth>
    <writeHeight>512</writeHeight>
  </destination>
  
</root>

=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/fontverdana.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/fontspliter.xsd"
      >
  <source>
    <spaceWidth>22</spaceWidth>
    <newLine>54</newLine>
    <image>
      <filePath>font\veranda_00.tga</filePath>
      <charSequence>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890`~!@#$%^*()_+-=[]{};':,./?\|&#169;&#60;&#62;&#38;"</charSequence>
      <baseLine>78</baseLine>
    </image>
  </source>

  <destination>
    <destinationPath>fontveranda\</destinationPath>
    <tagetTexture>font.tga</tagetTexture>
    <targetWidth>2048</targetWidth>
    <targetHeight>2048</targetHeight>
    <writeOriginX>642</writeOriginX>
    <writeOriginY>0</writeOriginY>
    <writeWidth>1406</writeWidth>
    <writeHeight>512</writeHeight>
  </destination>
</root>

=== DavidCoenFish/ancient-code-0/beachvolleyball/monkey/fontcourier.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/fontspliter.xsd"
      >
  <source>
    <spaceWidth>22</spaceWidth>
    <newLine>26</newLine>
    <image>
      <filePath>fontcourier\fontcourier.tga</filePath>
      <charSequence>abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890`~!@#$%^*()_+-=[]{};':",./?\|</charSequence>
      <baseLine>44</baseLine>
    </image>
    <image>
      <filePath>fontcourier\fontcourierextra.tga</filePath>
      <charSequence>&#169;&#60;&#62;&#38;</charSequence>
      <baseLine>44</baseLine>
    </image>
  </source>

  <destination>
    <destinationPath>fontcouriersplit\</destinationPath>
    <tagetTexture>font.tga</tagetTexture>
    <targetWidth>2048</targetWidth>
    <targetHeight>2048</targetHeight>
    <writeOriginX>512</writeOriginX>
    <writeOriginY>768</writeOriginY>
    <writeWidth>512</writeWidth>
    <writeHeight>256</writeHeight>
  </destination>
</root>
