=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/fudgepacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:simpleType name="u8">
    <xsd:restriction base="xsd:int">
      <xsd:minInclusive value="-1"/>
      <xsd:maxInclusive value="255"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="u16">
    <xsd:restriction base="xsd:int">
      <xsd:minInclusive value="-1"/>
      <xsd:maxInclusive value="65535"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="u32">
    <xsd:restriction base="xsd:long">
      <xsd:minInclusive value="-1"/>
      <xsd:maxInclusive value="4294967295"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:group ref="dataTypeGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="dataTypeGroup">
    <xsd:choice>
      <xsd:element name="u8" type="u8"/>
      <xsd:element name="u16" type="u16"/>
      <xsd:element name="u32" type="u32"/>
      <xsd:element name="r32" type="xsd:float"/>
      <xsd:element name="u8array" type="xsd:string"/>
      <xsd:element name="u16array" type="xsd:string"/>
      <xsd:element name="u32array" type="xsd:string"/>
      <xsd:element name="r32array" type="xsd:string"/>
      <xsd:element name="string" type="xsd:string"/>
      <xsd:element name="pointer" type="pointerType"/>
      <xsd:element name="reference" type="referenceType"/>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="pointerType">
    <xsd:sequence>
      <xsd:group ref="dataTypeGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="alignment" type="xsd:positiveInteger" use="optional"/>
    <xsd:attribute name="label" type="xsd:string" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="referenceType">
    <xsd:sequence/>
    <xsd:attribute name="label" type="xsd:string" use="optional"/>
  </xsd:complexType>


</xsd:schema>

=== DavidCoenFish/ancient-code-0/pipeline/data/fudgepackertest.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/FudgePacker.xsd">
    <u32>5</u32>
    <u32>74</u32>
    <u32>1</u32>
    <pointer alignment="4">
        <u8array>0D0D0E191819171916191519141913191219111910190F0D0D0D0D000F03100411051206130714081509160A170B180C0E020D02000103010401050106010701080109010A010B010C02</u8array>
    </pointer>
    <u32>26</u32>
    <u32>12</u32>
    <pointer alignment="4">
        <u8array>6DE70142D1913DC1000096C100000000D1913DC10000000000001642D1913DC10000000000009641D1913DC16DE701C2CC01DCB5D1913DC1000016C2000096C1D1913DC16DE701C26DE701C2D1913DC1000096C1000016C2D1913DC19BDFBDB66DE701C2D1913DC100009641000096C1D1913DC152E70142A93F92B7D1913DC10000164200009641D1913DC16DE7014252E70142D1913DC1000096416DE701421737CD41000096C1000016421737CD4100000000000096411737CD416DE701C2CC01DCB51737CD41000016C2000096C11737CD416DE701C26DE701C21737CD41000096C1000016C21737CD419BDFBDB66DE701C21737CD4100009641000096C11737CD4152E70142A93F92B71737CD4100001642000096411737CD416DE7014252E701421737CD4100009641000000008C9B314200000000</u8array>
    </pointer>
    <u32>1</u32>
    <pointer alignment="4">
        <u32>5126</u32>
        <u32>3</u32>
        <u32>1</u32>
        <u32>0</u32>
    </pointer>
    <u32>0</u32>
    <u32>0</u32>
    <pointer alignment="4" />
    <string></string>
</root>
