=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/guipacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  
  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="gui" type="guiType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="guiType">
    <xsd:sequence>
      <xsd:element name="node" type="nodeType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="nodeType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" />

      <xsd:element name="flagSquareMin" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
      <xsd:element name="flagSquareMax" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
      <xsd:element name="flagSquareVertical" type="xsd:boolean" minOccurs="0" maxOccurs="1" />
      <xsd:element name="flagSquareHorizontal" type="xsd:boolean" minOccurs="0" maxOccurs="1" />

      <xsd:element name="originRatioX" type="xsd:float" />
      <xsd:element name="originRatioY" type="xsd:float" />
      <xsd:element name="originOffsetX" type="xsd:float" />
      <xsd:element name="originOffsetY" type="xsd:float" />

      <xsd:element name="sizeRatioX" type="xsd:float" />
      <xsd:element name="sizeRatioY" type="xsd:float" />
      <xsd:element name="sizeOffsetX" type="xsd:float" />
      <xsd:element name="sizeOffsetY" type="xsd:float" />

      <xsd:group ref="componentTypeGroup" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="node" type="nodeType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="componentTypeGroup">
    <xsd:choice>
      <xsd:element name="componentPanel" type="componentPanelType"/>
      <xsd:element name="componentText" type="componentTextType"/>
      <xsd:element name="componentButton" type="componentButtonType"/>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="componentPanelType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string" />
      <xsd:element name="flagVisible" type="xsd:boolean"/>
      <xsd:element name="flagColour1" type="xsd:boolean" />
      <xsd:element name="flagColour4" type="xsd:boolean" />

      <xsd:element name="red0" type="xsd:float" minOccurs="0" />
      <xsd:element name="green0" type="xsd:float" minOccurs="0" />
      <xsd:element name="blue0" type="xsd:float" minOccurs="0" />
      <xsd:element name="alpha0" type="xsd:float" minOccurs="0" />
      
      <xsd:element name="red1" type="xsd:float" minOccurs="0" />
      <xsd:element name="green1" type="xsd:float" minOccurs="0" />
      <xsd:element name="blue1" type="xsd:float" minOccurs="0" />
      <xsd:element name="alpha1" type="xsd:float" minOccurs="0" />
      
      <xsd:element name="red2" type="xsd:float" minOccurs="0" />
      <xsd:element name="green2" type="xsd:float" minOccurs="0" />
      <xsd:element name="blue2" type="xsd:float" minOccurs="0" />
      <xsd:element name="alpha2" type="xsd:float" minOccurs="0" />
      
      <xsd:element name="red3" type="xsd:float" minOccurs="0" />
      <xsd:element name="green3" type="xsd:float" minOccurs="0" />
      <xsd:element name="blue3" type="xsd:float" minOccurs="0" />
      <xsd:element name="alpha3" type="xsd:float" minOccurs="0" />

      <xsd:element name="flagUV" type="xsd:boolean" />
      <xsd:element name="UVTop" type="xsd:float" minOccurs="0" />
      <xsd:element name="UVLeft" type="xsd:float" minOccurs="0" />
      <xsd:element name="UVBottom" type="xsd:float" minOccurs="0" />
      <xsd:element name="UVRight" type="xsd:float" minOccurs="0" />

    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="componentTextType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="flagVisible" type="xsd:boolean"/>
      <xsd:element name="red" type="xsd:float"/>
      <xsd:element name="green" type="xsd:float"/>
      <xsd:element name="blue" type="xsd:float"/>
      <xsd:element name="alpha" type="xsd:float"/>
      <xsd:element name="fontName" type="xsd:string"/>
      <xsd:element name="text" type="xsd:string"/>
      <xsd:element name="scale" type="xsd:float"/>
      <xsd:element name="horizontalCharPad" type="xsd:float"/>
      <xsd:element name="maximumCharCount" type="xsd:integer"/>

    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="componentButtonType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="actionScriptButtonDown" type="xsd:string"/>
      <xsd:element name="actionScriptButtonPress" type="xsd:string"/>
      <xsd:element name="actionScriptButtonCancel" type="xsd:string"/>
      <xsd:element name="actionScriptButtonEnable" type="xsd:string"/>
      <xsd:element name="actionScriptButtonDisable" type="xsd:string"/>

    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== DavidCoenFish/ancient-code-0/pipeline/data/gui.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/GuiPacker.xsd"
      >
  <gui>
    <node>
      <name>NodePlay01</name>
      <flagSquareMin>false</flagSquareMin>
      <flagSquareMax>false</flagSquareMax>
      <originRatioX>0.5</originRatioX>
      <originRatioY>1.0</originRatioY>
      <originOffsetX>-127.0</originOffsetX>
      <originOffsetY>-124.0</originOffsetY>
      <sizeRatioX>0.0</sizeRatioX>
      <sizeRatioY>0.0</sizeRatioY>
      <sizeOffsetX>254.0</sizeOffsetX>
      <sizeOffsetY>62.0</sizeOffsetY>
      <componentText>
        <name>Text10</name>
        <flagVisible>true</flagVisible>
        <red>1.0</red>
        <green>0.521569</green>
        <blue>0.0</blue>
        <alpha>1.0</alpha>
        <fontName>fontcourier.data</fontName>
        <text>Play</text>
        <scale>0.75</scale>
        <horizontalCharPad>1.0</horizontalCharPad>
        <maximumCharCount>4</maximumCharCount>
      </componentText>
    </node>
  </gui>
</root>
