=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/materialpacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:simpleType name="blendModeEnum">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TZero"/>
      <xsd:enumeration value="TOne"/>
      <xsd:enumeration value="TSrcColor"/>
      <xsd:enumeration value="TOneMinusSrcColor"/>
      <xsd:enumeration value="TDstColor"/>
      <xsd:enumeration value="TOneMinusDstColor"/>
      <xsd:enumeration value="TSrcAlpha"/>
      <xsd:enumeration value="TOneMinusSrcAlpha"/>
      <xsd:enumeration value="TDstAlpha"/>
      <xsd:enumeration value="TOneMinusDstAlpha"/>
      <xsd:enumeration value="TSrcAlphaSaturate"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="faceCW" type="xsd:boolean"/>
      <xsd:element name="faceCull" type="xsd:boolean"/>
      <xsd:element name="colourWrite" type="xsd:boolean"/>

      <xsd:element name="textureDataName" type="xsd:string"/>
      <xsd:element name="useTexture" type="xsd:boolean"/>
      <xsd:element name="red" type="xsd:float"/>
      <xsd:element name="green" type="xsd:float"/>
      <xsd:element name="blue" type="xsd:float"/>
      <xsd:element name="alpha" type="xsd:float"/>
      <xsd:element name="alphaBlend" type="xsd:boolean"/>
      <xsd:element name="blendModeSrc" type="blendModeEnum"/>
      <xsd:element name="blendModeDst" type="blendModeEnum"/>
      
      <xsd:element name="depthRead" type="xsd:boolean"/>
      <xsd:element name="depthWrite" type="xsd:boolean"/>

      <xsd:element name="stencilShadowFront" type="xsd:boolean"/>
      <xsd:element name="stencilShadowBack" type="xsd:boolean"/>
      <xsd:element name="stencilShadow" type="xsd:boolean"/>

      <xsd:element name="useLighting" type="xsd:boolean"/>
      
      <xsd:element name="doBasePass" type="xsd:boolean"/>
      <xsd:element name="doEnvironmentPass" type="xsd:boolean"/>
      <xsd:element name="environmentUVTile" type="xsd:int"/>
      <xsd:element name="environmentUVIndex" type="xsd:int"/>
      
      <xsd:element name="vertexFileName" type="xsd:string"/>
      <xsd:element name="fragmentFileName" type="xsd:string"/>
      
      <xsd:element name="attributeNameArray" type="stringArrayType"/>
      <xsd:element name="uniformNameArray" type="stringArrayType"/> 
      
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:int"/>
  </xsd:complexType>

  <xsd:complexType name="stringArrayType">
    <xsd:sequence>
      <xsd:element name="item" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>
  
</xsd:schema>

=== DavidCoenFish/ancient-code-0/pipeline/data/material.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Schema/MaterialPacker.xsd"
      >
		<faceCW>true</faceCW>
		<faceCull>true</faceCull>
		<colourWrite>true</colourWrite>
		<textureDataName>texture.data</textureDataName>
		<useTexture>true</useTexture>
		<red>1.0</red>
		<green>1.0</green>
		<blue>1.0</blue>
		<alpha>1.0</alpha>
		<alphaBlend>true</alphaBlend>
		<blendModeSrc>TSrcAlpha</blendModeSrc>
		<blendModeDst>TOneMinusSrcAlpha</blendModeDst>
		<depthRead>true</depthRead>
		<depthWrite>false</depthWrite>
		<stencilShadowFront>false</stencilShadowFront>
		<stencilShadowBack>false</stencilShadowBack>
		<stencilShadow>false</stencilShadow>
		<useLighting>false</useLighting>
		<doBasePass>false</doBasePass>
		<doEnvironmentPass>false</doEnvironmentPass>
		<environmentUVTile>1</environmentUVTile>
		<environmentUVIndex>0</environmentUVIndex>
		<vertexFileName>vertexshadergroundalpha.txt</vertexFileName>
		<fragmentFileName>fragmentshadergroundalpha.txt</fragmentFileName>
		<attributeNameArray>
			<item>a_position</item>
			<item>a_colour</item>
			<item>a_uv0</item>
		</attributeNameArray>
		<uniformNameArray>
			<item>u_mvpMatrix</item>
		</uniformNameArray>
</root>
