=== DavidCoenFish/ancient-code-0/zombie2/zombie2/monkey/schema/missionpacker.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

  <xsd:simpleType name="transitionTypeEnum">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="TLinear"/>
      <xsd:enumeration value="TEaseInOut"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:element name="root" type="rootType" />

  <xsd:complexType name="rootType">
    <xsd:sequence>
      <xsd:element name="mission" type="missionType"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="missionType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="sequenceArray" type="sequenceArrayType"/>
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="sequenceArrayType">
    <xsd:sequence>
      <xsd:element name="sequence" type="sequenceType" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="sequenceType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="key" type="keyType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="keyType">
    <xsd:sequence>
      <xsd:element name="time" type="xsd:float"/>
      <xsd:group ref="dataTypeGroup"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:group name="dataTypeGroup">
    <xsd:choice>
      <xsd:element name="dataAnimateClientTrigger" type="dataAnimateClientTriggerType"/>
      <xsd:element name="dataAnimateClientTriggerFloat" type="dataAnimateClientTriggerFloatType"/>
      <xsd:element name="dataAnimateClientTriggerString" type="dataAnimateClientTriggerStringType"/>
      <xsd:element name="dataAnimateClientTriggerVector" type="dataAnimateClientTriggerVectorType"/>
      <xsd:element name="dataAnimateClientTriggerVectorVector" type="dataAnimateClientTriggerVectorVectorType"/>
      <xsd:element name="dataClientTrigger" type="dataClientTriggerType"/>
      <xsd:element name="dataClientTriggerFloat" type="dataClientTriggerFloatType"/>
      <xsd:element name="dataClientTriggerString" type="dataClientTriggerStringType"/>
      <xsd:element name="dataClientTriggerVector" type="dataClientTriggerVectorType"/>
      <xsd:element name="dataClientTriggerVectorVector" type="dataClientTriggerVectorVectorType"/>
      <xsd:element name="dataLoopSequence" type="dataLoopSequenceType"/>
      <xsd:element name="nop" type="nopType"/>
      <xsd:element name="dataPlayAnimation" type="dataPlayAnimationType"/>
      <xsd:element name="dataTriggerSequence" type="dataTriggerSequenceType"/>
    </xsd:choice>
  </xsd:group>

  <xsd:complexType name="dataAnimateClientTriggerType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="lerpDuration" type="xsd:float"/>
      <xsd:element name="lerpType" type="transitionTypeEnum"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataAnimateClientTriggerFloatType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="value" type="xsd:float"/>
      <xsd:element name="lerpDuration" type="xsd:float"/>
      <xsd:element name="lerpType" type="transitionTypeEnum"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataAnimateClientTriggerStringType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="value" type="xsd:string"/>
      <xsd:element name="lerpDuration" type="xsd:float"/>
      <xsd:element name="lerpType" type="transitionTypeEnum"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataAnimateClientTriggerVectorType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="valueX" type="xsd:float"/>
      <xsd:element name="valueY" type="xsd:float"/>
      <xsd:element name="valueZ" type="xsd:float"/>
      <xsd:element name="lerpDuration" type="xsd:float"/>
      <xsd:element name="lerpType" type="transitionTypeEnum"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataAnimateClientTriggerVectorVectorType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="valueOneX" type="xsd:float"/>
      <xsd:element name="valueOneY" type="xsd:float"/>
      <xsd:element name="valueOneZ" type="xsd:float"/>
      <xsd:element name="valueTwoX" type="xsd:float"/>
      <xsd:element name="valueTwoY" type="xsd:float"/>
      <xsd:element name="valueTwoZ" type="xsd:float"/>
      <xsd:element name="lerpDuration" type="xsd:float"/>
      <xsd:element name="lerpType" type="transitionTypeEnum"/>
    </xsd:sequence>
  </xsd:complexType>  
  
  <xsd:complexType name="dataClientTriggerType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataClientTriggerFloatType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="value" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataClientTriggerStringType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="value" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataClientTriggerVectorType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="valueX" type="xsd:float"/>
      <xsd:element name="valueY" type="xsd:float"/>
      <xsd:element name="valueZ" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataClientTriggerVectorVectorType">
    <xsd:sequence>
      <xsd:element name="clientTrigger" type="xsd:string"/>
      <xsd:element name="data" type="xsd:string"/>
      <xsd:element name="valueOneX" type="xsd:float"/>
      <xsd:element name="valueOneY" type="xsd:float"/>
      <xsd:element name="valueOneZ" type="xsd:float"/>
      <xsd:element name="valueTwoX" type="xsd:float"/>
      <xsd:element name="valueTwoY" type="xsd:float"/>
      <xsd:element name="valueTwoZ" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="nopType">
    <xsd:sequence>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataTriggerSequenceType">
    <xsd:sequence>
      <xsd:element name="sequenceName" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataPlayAnimationType">
    <xsd:sequence>
      <xsd:element name="actorName" type="xsd:string"/>
      <xsd:element name="animationName" type="xsd:string"/>
      <xsd:element name="rate" type="xsd:float" minOccurs="0"/>
      <xsd:element name="fadeTime" type="xsd:float" minOccurs="0"/>
      <xsd:element name="startTime" type="xsd:float" minOccurs="0"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="dataLoopSequenceType">
    <xsd:sequence>
      <xsd:element name="gotoTime" type="xsd:float"/>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>

=== DavidCoenFish/ancient-code-0/pipeline/data/mission.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!-- DSC Dsc Export 2010 09 16 -->
<root
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="schema/missionpacker.xsd"
      >
	<mission>
		<name>Mission01</name>
		<sequenceArray>
			<sequence>
				<name>foo</name>
				<key>
					<time>0.0</time>
					<dataPlayAnimation>
						<actorName>foo</actorName>
						<animationName>bar</animationName>
						<rate>0.99</rate>
						<fadeTime>0.1566</fadeTime>
						<startTime>0.0</startTime>
					</dataPlayAnimation>
				</key>
				<key>
					<time>0.0</time>
					<dataAnimateClientTrigger>
						<clientTrigger>aa</clientTrigger>
						<data>bb</data>
						<lerpDuration>0.01</lerpDuration>
						<lerpType>TLinear</lerpType>
					</dataAnimateClientTrigger>
				</key>
				<key>
					<time>0.0</time>
					<dataAnimateClientTriggerFloat>
						<clientTrigger>aa</clientTrigger>
						<data>vv</data>
						<value>0.1</value>
						<lerpDuration>0.02</lerpDuration>
						<lerpType>TLinear</lerpType>
					</dataAnimateClientTriggerFloat>
				</key>
				<key>
					<time>0.0</time>
					<dataAnimateClientTriggerString>
						<clientTrigger>a</clientTrigger>
						<data>v</data>
						<value>c</value>
						<lerpDuration>0.01</lerpDuration>
						<lerpType>TLinear</lerpType>
					</dataAnimateClientTriggerString>
				</key>
				<key>
					<time>0.0</time>
					<dataAnimateClientTriggerVector>
						<clientTrigger>a</clientTrigger>
						<data>c</data>
						<valueX>-5.69379</valueX>
						<valueY>0.0</valueY>
						<valueZ>-72.8905</valueZ>
						<lerpDuration>0.01</lerpDuration>
						<lerpType>TEaseInOut</lerpType>
					</dataAnimateClientTriggerVector>
				</key>
				<key>
					<time>0.0</time>
					<dataAnimateClientTriggerVectorVector>
						<clientTrigger>a</clientTrigger>
						<data>c</data>
						<valueOneX>0.0</valueOneX>
						<valueOneY>0.0</valueOneY>
						<valueOneZ>1.0</valueOneZ>
						<valueTwoX>0.0</valueTwoX>
						<valueTwoY>1.0</valueTwoY>
						<valueTwoZ>0.0</valueTwoZ>
						<lerpDuration>0.01</lerpDuration>
						<lerpType>TEaseInOut</lerpType>
					</dataAnimateClientTriggerVectorVector>
				</key>
				<key>
					<time>0.0</time>
					<dataClientTrigger>
						<clientTrigger>s</clientTrigger>
						<data>f</data>
					</dataClientTrigger>
				</key>
				<key>
					<time>0.0</time>
					<dataClientTriggerFloat>
						<clientTrigger>a</clientTrigger>
						<data>d</data>
						<value>0.1</value>
					</dataClientTriggerFloat>
				</key>
				<key>
					<time>0.02</time>
					<dataClientTriggerString>
						<clientTrigger>a</clientTrigger>
						<data>s</data>
						<value>d</value>
					</dataClientTriggerString>
				</key>
				<key>
					<time>0.0</time>
					<dataClientTriggerVector>
						<clientTrigger>a</clientTrigger>
						<data>d</data>
						<valueX>6.13202</valueX>
						<valueY>0.0</valueY>
						<valueZ>-73.3063</valueZ>
					</dataClientTriggerVector>
				</key>
				<key>
					<time>0.0</time>
					<dataClientTriggerVectorVector>
						<clientTrigger>a</clientTrigger>
						<data>c</data>
						<valueOneX>0.0</valueOneX>
						<valueOneY>0.0</valueOneY>
						<valueOneZ>1.0</valueOneZ>
						<valueTwoX>0.0</valueTwoX>
						<valueTwoY>1.0</valueTwoY>
						<valueTwoZ>0.0</valueTwoZ>
					</dataClientTriggerVectorVector>
				</key>
				<key>
					<time>0.5</time>
					<dataLoopSequence>
						<gotoTime>0.01</gotoTime>
					</dataLoopSequence>
				</key>
				<key>
					<time>10.0</time>
					<nop/>
				</key>
			</sequence>
		</sequenceArray>
	</mission>
</root>
